# Generated by Django 5.0.3 on 2025-01-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_options_alter_machine_status'),
        ('operators', '0002_alter_operator_options'),
        ('services', '0002_alter_service_options_alter_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='service',
            name='operator',
        ),
        migrations.AddField(
            model_name='service',
            name='machines',
            field=models.ManyToManyField(to='machines.machine'),
        ),
        migrations.AddField(
            model_name='service',
            name='operators',
            field=models.ManyToManyField(to='operators.operator'),
        ),
    ]
