# Generated by Django 5.0.3 on 2025-01-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_options_alter_machine_status'),
        ('operators', '0002_alter_operator_options'),
        ('services', '0003_remove_service_machine_remove_service_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='client',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='service',
            name='machines',
            field=models.ManyToManyField(to='machines.machine', verbose_name='Máquinas'),
        ),
        migrations.AlterField(
            model_name='service',
            name='operators',
            field=models.ManyToManyField(to='operators.operator', verbose_name='Operadores'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Active', 'Ativo'), ('Inactive', 'Inativo')], max_length=50, verbose_name='Status'),
        ),
    ]
