# Generated by Django 5.0.3 on 2025-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_client_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('To Do', 'Fazer'), ('In Progress', 'Em progresso'), ('Done', 'Finalizado')], max_length=50, verbose_name='Status'),
        ),
    ]
