# Generated by Django 5.0.3 on 2025-01-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exit',
            options={'verbose_name': 'Saída', 'verbose_name_plural': 'Saídas'},
        ),
    ]
