# Generated by Django 5.0.3 on 2025-01-08 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categoryentry_description_and_more'),
        ('exits', '0002_alter_exit_options'),
        ('machines', '0003_alter_machine_description_alter_machine_name_and_more'),
        ('operators', '0003_alter_operator_name_alter_operator_phone'),
        ('services', '0004_alter_service_client_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categoryexit', verbose_name='Categoria de Saída'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_date',
            field=models.DateTimeField(verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.operator', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Serviço'),
        ),
    ]
