# Generated by Django 5.0.3 on 2025-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exits', '0003_alter_exit_category_alter_exit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AddField(
            model_name='exit',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
    ]
