# Generated by Django 5.0.3 on 2025-01-08 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exits', '0004_exit_price_exit_total_value'),
        ('machines', '0003_alter_machine_description_alter_machine_name_and_more'),
        ('operators', '0003_alter_operator_name_alter_operator_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operators.operator', verbose_name='Operador'),
        ),
    ]
