# Generated by Django 5.0.3 on 2025-01-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exits', '0005_alter_exit_machine_alter_exit_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário'),
        ),
    ]
