# Generated by Django 5.0.3 on 2025-01-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
    ]
