# Generated by Django 5.0.3 on 2025-01-08 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_alter_operator_name_alter_operator_phone'),
        ('services', '0004_alter_service_client_alter_service_description_and_more'),
        ('tasks', '0002_alter_tasks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='horimeter_end',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Leitura Final do Horímetro (Horas)'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='horimeter_start',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Leitura Inicial do Horímetro (Horas)'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Horas Trabalhadas'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.operator', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
    ]
