# Generated by Django 5.0.3 on 2025-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_created_at_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Hora'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='service_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Serviço'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
    ]
