# Generated by Django 5.0.3 on 2025-01-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_hourly_rate_tasks_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Serviço'),
        ),
    ]
