# Generated by Django 5.0.3 on 2025-01-08 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_description_alter_machine_name_and_more'),
        ('tasks', '0005_alter_tasks_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machine', verbose_name='Máquina'),
        ),
    ]
