# Generated by Django 5.0.3 on 2025-01-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
