# Generated by Django 5.0.3 on 2025-01-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_machine_alter_entry_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
    ]
