# Generated by Django 5.0.3 on 2025-01-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_price_entry_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitário'),
        ),
    ]
