# Generated by Django 5.0.3 on 2025-01-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryentry',
            options={'verbose_name': 'Categoria de Entrada', 'verbose_name_plural': 'Categorias de Entrada'},
        ),
        migrations.AlterModelOptions(
            name='categoryexit',
            options={'verbose_name': 'Categoria de Saída', 'verbose_name_plural': 'Categorias de Saída'},
        ),
    ]
