# Generated by Django 5.0.3 on 2025-01-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categoryentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoryentry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoryexit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoryexit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
