# Generated by Django 5.0.3 on 2025-01-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('Active', 'Ativo'), ('Inactive', 'Inativo')], max_length=50),
        ),
    ]
